# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

btm <- function(biterms, x, K, W, alpha, beta, iter, win = 15L, background = FALSE, trace = 0L) {
    .Call('_BTM_btm', PACKAGE = 'BTM', biterms, x, K, W, alpha, beta, iter, win, background, trace)
}

btm_infer <- function(model, x, type) {
    .Call('_BTM_btm_infer', PACKAGE = 'BTM', model, x, type)
}

btm_biterms <- function(btm_model) {
    .Call('_BTM_btm_biterms', PACKAGE = 'BTM', btm_model)
}

btm_biterms_text <- function(x, W, win = 15L) {
    .Call('_BTM_btm_biterms_text', PACKAGE = 'BTM', x, W, win)
}

