# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

btm <- function(x, K, W, alpha, beta, iter, win = 15L, background = FALSE, trace = 0L) {
    .Call('_BTM_btm', PACKAGE = 'BTM', x, K, W, alpha, beta, iter, win, background, trace)
}

btm_infer <- function(model, x, type) {
    .Call('_BTM_btm_infer', PACKAGE = 'BTM', model, x, type)
}

